server:
  port: 8763

spring:
  application:
    name: eureka-client-test2
eureka:
  instance:
    #以IP地址注册到服务中心，相互注册使用IP地址
    preferIpAddress: true
    instance-id: localhost:8763
  client:
    #eureka server注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/